language: java
jdk:
- oraclejdk8
env:
  global:
  - ACTIVATOR_VERSION=1.3.7
  - ACTIVATOR_ZIP_FILE=typesafe-activator-${ACTIVATOR_VERSION}-minimal.zip
  - ACTIVATOR_ZIP_URL=http://downloads.typesafe.com/typesafe-activator/${ACTIVATOR_VERSION}/${ACTIVATOR_ZIP_FILE}
  - PLAY2_HOME=${TRAVIS_BUILD_DIR}/activator-${ACTIVATOR_VERSION}-minimal
  - SBT_EXECUTABLE_NAME=activator
  - GH_REF=github.com/theAgileFactory/app-framework
  - secure: VB5Lspbxb1P4Zbznn7wKMN89pty1sTCQfLPHSF8nOvVyiZzPaxqHfFmxYbaeUulkVdlRwVmBOvmOivtZ9a+/P9g5oato2PvtN+PeMJzIsZRgJ3QvnaC5CqeDzsXzrwHU1i8y/A601TvNeBDAwazH458+MJyXkCE+QQ/XamvrVioVaVbDLxooQEI4V6FVOePsRQMx80jgupixRJvrbCGXC85xNyilOZcAu/OXm4JXmeAvMh7M0as7K6WFY2yOFDM3tyzctiyAdsBjNoYcZqKHPWqlmtQLk0IewSggBz+m1jv8ORUJipepF+pmKvVKkXuwrHxPDTJp5qRIf9TVDMWOYt0kXoD9FC0d7kdCMVzHNnfn/WlQqSSUHuORYDhA9H3mdeKupHEhMJcCtFF1f+OCIQP6ra9S78uNKC8lTM2K1OiD1J3G104IiJ9ckoDsHLXoGtfm+d2VGbLw77RhXxLz5tNynmCJ9Sa3hRMONXaHMutq6jVa3+DZzut+jxlmEKPSuJH1oXMVHjdnSjZswlDfgbWR7KLGHwqg1keayViAhhsds9s+Do1oCSLlnhqVxa/0yEvZisXoGmVsTUIpUt5lXFp/IQ+2Y27M/HoUprnLZ0JPrJkuV9KRvDa2LbPZnEujWGlUMd9z6qkd5CHJcrM1+cBciyNwAgqfrbwCWeryHtY=
  - secure: hC1weZHe1ygSV81Vk1HJhPPxtHp/ufvtrL89qHdiVLVTd6hPpTKM5zb4Y+4864cjLoR+Czs1gWo+aVzu5/rbkrwm7jM9Ug8+U3Y28cnpRErLEzN3P7b1zLBiaN1kF1QpPW6kHIQJXNizfjtxrga6kEYfVt1LVhQzyI0fwMPNAB9b3oMi751Vvj4GgYPJCJiIqXh35nywDD2RKH2UyJLYDr+bKwWyFwWm/GSJ2YSzn715QuhpFnJJy5XrC18DOPiuiIL0Ata5GloTd4nBgt7B6CuQfbtfuVRBVDW0QDWaaYp7BuD01mpBK4OfF8ZMyWoieKgnT8lpsBbO+414e9MV/XhREXv9VZuQHohJuK8LPP2+ri2k229O741n892SIlR3FBWTqLqDtdCYOL6UxFrGRsr3OGlvBVz8MVveKcAZzmpU55k4ArRLPPRT4Vnrn1E4FeTdbNtzrxq/WBf57h+I5M7JwX9FqZbcLwEZbq7rGwcmOUMk8yc1Y+3HlIfIh0FuusNguLWk5fOgyE5HgcGGW5+02lDUFqAG3RQxTrOU2wDBsgC6IRKUQWnTwxF7q/jR3qu4Pojdu4UM5nNGneEd20cLNTXy17Fli8Dlw174fCa0MqgkkgB7+7MG7PmQEv5SeIjudjNZUP+N0/bR8rBH95EqkLBISua1PAvMIOLxTRE=
  - secure: H8xDEYiSQnS+awnjpPakZqaeYVW24tI6CPCm+V+/I58fGTDDrNhREuHdE6EjEyatz5GVwOtgg7SDwUE1t6jmUGHpiZxKS973yEI+JQzeg5wqSEjyl9kV8JCOJdFGUgMhn3/khf7Zwn83ScpAs2flhYh4NzUHBesU270SyYNNrkfC8BOJtgZpWGrtC59lGVyLzyugqz/XsFvF8UfcQTHwKGS+hul/oaSUFpqs7KE1Z2BRe851o5J/DqTVaNRK4BtJ93CeqLnk7yuHwaRegwEpcvcF/GC2QM8i2xzEwlE74p12zBSL/R3PJw5QbqT7sCuCftpt0Dd1ZyTpi5n5NakhGxe9cu/2b6RLsA+CSuDj7Evc5/tUZPuqI8O5VS2K1kN5QHdO+mQz2wzvwBgkC6v3qpYRQuOlxYvb8gk+WZeR64ffS3JKEZRYWW9Q6Sa+EIj76MWffPgwg5hHwhSdaQQ/mB+qXS1WLcdr1K3eWwgCIgSLHS757COtR/cOmxM/0W476EPkbN9SINN0Oby67VmePqalLRRf9nMFHJMuCdsU8MWH9lbSxSaHKNiuqWC/prAWP2J/cUCEpwwtK8E6UH+MbSh5xXrptetyrmpwrrV1g94BRH0IlYQS1DZ9qBn9jqxiU4VuWrf3XuuifZ8Pu1XebXjpjzKs829bFyXEijGMRSw=
  - secure: FlZPWXbDvqd17iH2yDQ2W4JSnnrYBNZPSeAOMNxgI5RlcuEd73Jgki46Don6Wc4RzeC36Evepoea0zeSGNCmG4QstK7R6biAw1K61L51WCV2P2+mQR16/QYsOjNTQt81ks3kYhcJPuUZ/IjsatGjJsaXRenZ6kqPx8ngprAqaFT0lq5UPSJfGWVBB7kGJPwRInB7aIk9TG63Dm8KNEGTNcE55EBnAx/GI28XZWVk0yGczfqRUuBTDvI/2JGedRE7tN9cGAwZJuphWaqnUiNm2XeeyWgaReTMSZ2h0JjSdZX0kazdS3L1z1lfQd32fCaWjrlv5rTjDXbmppCNMrnKUJIDFmiYIBFOyMfpVlXXmufE1A7fSwBrwWnpZvM89vfzvURdW1ZWfDajGTfiG95Gynh/R1f/CWSczDwKqI1aAV4iOd/k0wpDKANN/XX5DEM6lMxU+LtAqbip83wRxrIQCBofdeEv/nN8PpMJtmjEhScO2eQpKWwV65sCQyaRzNdXjHmHXj7WpzyX48Gc0nMyaWgFXyokFyvZhsTq/8/CmJ9Gc12v6cOukMN6HT3y/lZQ0EFo5M/WrslbxCJkFyYqsdY8UGWGbHdD/84AOm2vucYZEpjzVoeBbE1lRczeESFQUEPk9/ADKyxg0gxaZ/h5uUjg/OMK+ZarWEHslmo2yVw=
before_install:
- sudo apt-get update
- sudo apt-get install --only-upgrade -y oracle-java8-installer
- mkdir -p ~/.gnupg
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in secring.gpg.enc -out ~/.gnupg/secring.gpg
  -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in pubring.gpg.enc -out ~/.gnupg/pubring.gpg
  -d
- echo "<settings><servers><server><id>ossrh</id><username>\${OSSRH_JIRA_USERNAME}</username><password>\${OSSRH_JIRA_PASSWORD}</password></server></servers></settings>"
  > ~/.m2/settings.xml
install:
- wget ${ACTIVATOR_ZIP_URL}
- unzip -q ${ACTIVATOR_ZIP_FILE}
script:
- mvn -f pom2.xml clean install gpg:sign -Dgpg.passphrase="${GPG_PASSPHRASE}" --settings
  ~/.m2/settings.xml
after_success:
- .travis/deploy.sh
after_script:
- rm ~/.gnupg/secring.gpg
- rm ~/.gnupg/pubring.gpg
- rm ~/.m2/settings.xml
notifications:
  email: true
branches:
  only:
  - master
scala:
- 2.11.8
cache:
  directories:
  - .autoconf
  - ~/.m2
  - ~/.sbt
  - ~/.ivy
