language: java
jdk:
- oraclejdk8
env:
  global:
  - ACTIVATOR_VERSION=1.3.7
  - ACTIVATOR_ZIP_FILE=typesafe-activator-${ACTIVATOR_VERSION}-minimal.zip
  - ACTIVATOR_ZIP_URL=http://downloads.typesafe.com/typesafe-activator/${ACTIVATOR_VERSION}/${ACTIVATOR_ZIP_FILE}
  - PLAY2_HOME=${TRAVIS_BUILD_DIR}/activator-${ACTIVATOR_VERSION}-minimal
  - SBT_EXECUTABLE_NAME=activator
  - GH_REF=github.com/theAgileFactory/app-framework
  - secure: z6R9MBtV6Qrxk3FXQhYDzdbXTUsFcSNMwgtbo1O5Ev5VjsUeDijDrjMo8Z6Sl2pE1cqOomi69OxkH/axv6Goi2jPw5vNOwguh63Yr6F3FoletbdUf7gW58sYN17K5e6Lon12YLgCGjM6YqrtQR+qNvn+O319Wa61Kg/lyX6f+wOX4dmy9X4woMcjH6IX1c6SRDt6ukff/sxmPJpzP/1o+KS2sKVrYVKV7roh4Mhpkm3dO8PXKNj6pKXX2N4rd8lkSB2UGuh4zH8Zhkt8hdGLE3lvw0d/YL5Me67EGQvrEBWTiXI6p1gFvIXsM9Dq0vX9AasUo0Yy0FeTGd8YRgRXmmwmxA0xv86C04nStyOoXdiGWInejrBbCFoteR2En0zHvov82cYs/SoMnqXAOO0NoUspW35A3CaKJ/5RcA3dg2I8t2jIa5nefHf5tJizkaQaJDUFkzbkz8jU/7nb2DcjQUdfnYlEjzZLPpohoIzV4TsqCjklLbc8HdD5GuHHV6zXX1oqLJ0d6lRfBuauPdqmk7tDAW+jiUuuiOD9gUmQklVUZuuYhchyVvSBOx2mCYlbheGU/j9+eQ5os/avuZcIr7sH5Hq327FMyw1PH2xtTEMk9gozb4ZTMt0ocV6b4eaJ5Qaqh4q3xTGkgvrGENWAcoMcBckoMQmzUUglvCi3wGU=
  - secure: j13+aIxLmI7zgBH9S75Vvkb0AZrt3eOSNH1X09WGJAJgka1KFjnIdUfSqq58cgA62GHCgyIAuehwUlfK0lTNgsu75qcZF8M/SGL7lw33L4fJa9JrwnNEyV+1gARUyhWjO3IagFaLI4LXBQjhUlcfPUOMhCNzgc10/7aoFym7C5mF6YH1onL+ryZfhwsgZuFVScaoCVvw4KYup3FTcPzEaWDOlMLgAGhx1gSu4h7MILL+erWirLJnLE0P7iyjWVIQwspHKj7DKmZeXrDUYCB7gLRLUFrLp9riwEZt5p3zccVFEwVz/zCcG7CQ4jLxZRsWZx1/PjLDj3iM631UoQsNqvjH/h1mha/hU4NLQ9gA95RHor32LJ9+BDpc+aUDHyuHQ+5t4wbfCk4lYUbczhZduvXtFRlhRtiE3MUjfyPGxsw0kk0O68G6tSU+ZxjpGe5gx/zGTaamwhWZjNPYafzxl7UOWSWxg8HetKtrMVn8S5VYVliGHtdl5IoSJZfkB1ZLKmVLjYt1ZMZ3fMRe+mzYIWRzMsL3RxsEO6GAu6E0EeLwEzgi4MeHA5uVCetVaTaNA0sHNuY20rP7eShuzM8or74MDX4T3aH/5TxK3HlmKZW2RgE43HQvN70zJ2gri1wjWpZn9dzoR3dCad7UnbhDVxtVn5q7nmcL2kIktlDNI1U=
  - secure: EYzCfPM1P1b0kNnd2Se05aYAvUKHDz2lz1upUThmwBSqNlkoAGXi/UlEnmUjhjVx9i5aDlV5TazAgRS2CPi1+/7iTBLLzNkQ4qtCFqIO7p/BIEuGuTMmMIOaXSq5kHncdviIq1hROVQsHdG4cf8rIZtNdqhp8KSCp9vgQnZKF20rdGZop5DKkjy0O+/cqK6cA+U38+GWzh0OVk26H8tjrsRr08XgzzWzCqoS4zsOMZtPEmS/2kAKyLfHfBBU0BrvQTAG+YDsRIiYuQgVijY4FYTifVsvoiO/I6adCFBgtArqkHvqKAKJs4H88kKD5rPECVm+3cL4PeBx5TbJQXUurG1cvaKnUf7KwLuTxq+rW0O/eL3RGPTT5D3QauPnNzxcz4iSMRvSb+T80OfFroBEIFNRB2PbDt2Q0xN91j1Y5m52CXrfOltsXBx9i4G1f1RkG94qhi/epcXp6uae4lnnrjU0BZ43Ab9t0ENxfdrnO1RoAUcEwip73l/4W3g4kiZlPzAbXkXC6eN9+Xe22/KboUWxX//x/+IkwWLeXG6LFhgjcA2/m6EwQvxWG1si/Y+z4CJVPg6581JMPsS3JOu8bxobpZ7I0R/WCva624/vx9NDfHkuyr0I8Ch1uHPVgh/15iigp6gKzxOpBj3Pg63nXYOqdJJ0tWCkquL3jft3iqs=
  - secure: ZB5bAcBRu+TXjgAdXLNKKuUz2BKNx44H7GRc7aqXgjLdpttsBN4j5+gUCTtMAW4GtpR2Bqscpi0jcYRyc69r8dHd35M2/wq3Q68ISf8w6FXUFhPEDO0KVYt8wHdqXTHF7DC/poGQ1yVAkbWmnumSxF3GIR79NMFhpZftwSD626GDWV2iR8EQY8elSvmp5tIAMfbtcIyYA1DuRwuH+L4UQyj+/kccuJqZNVgfQg1XuFWVvsDpk02xx6mYa3otw2JB/J2CkwFNS+ZVPWpM9ZlKtilDSRlvwMKxYAQl55rY5cf4F1Bk4Ru7hiAuqvHC4h2EH2IZuQPLy/jVNlRANTMG5YywGxEmTyedZ58eDBf0iv3vip8R3RAZBjSZBQ+7XfqDOksEPLMqf27wI5ueoTsYuNXZUbqTq/sbmJ1FDNsTR5GVGeESU0+qzGki6Q1fvLvcs+1ID5298JgZQYUgSzNDylCJVa4eZd269tzkHRB4zSwHOWWi8fhkgj8YhSZSb52xXVS8C8HwkWoueR4R796UTQ3FYu745mm4qmcUYFrcRFC7TizL9412R8qIfQa7VQsP9S3jfZFh7mh1hBo/6vgLcovCJlDOb7s8YopEGgU6DYb7vNTFcyhaQHhuAgVQrN+BHyQ4L+cJvVYPAXwTbJnwJbg2EAxFE8juEaaRtOS3n8I=
  - secure: NwETBfY7F8J/EdDw5so1UFcOvPYDkNJFMK6IU+uKezjUF9+he5Y3kM0JbIEZLC0HqBq3lxhafVNg/lR4dKtbUMidxKHTMeFsrVIPq3jQCLyW/Edz7UI0iUaFkc9/CF9sA9OyCNEfUKk5qnrWeehse5Z2TqcVeViFyCUoxA7K3Ch1KVfuLhC2y5FHJSLH3IOOuKWhxG2EiuKP3eS5iXDh7P16GMiINpjXBp3vV2PiA+38grUKUmrs4P/N0W5rTQziEzR4dQIxGtt0Q3Kguua14AjlTjVw2FqpC2SuERAxaSj+g22X2uw9SnfpjPtp2XyI/I+0ImJoK2eGBOGHi5Ro6deT6vV/Q8yA3dyB89UJdannECUT429R/R7ibJP1TH99muElaH1/JxtXNYms57dr6slpltR1OiCz5Y63W8vQyh/ukanzQHPrAzVVOkQtMOV5joCyPMsImUU8cXGbEmaAPF/HszzGZY5FpPIJaHEE3xAhqtW01kgW3oa/nLK/9PooIECbOaxvfbW6D9irNKu71CUfOcAZeHEIog4q49lNIgiKGt3lrCer5BAztzpAgD8lSd5LT2OY9uzS02vzUHfIluyhB88c4CzAORdeHMoXNqIEv1Pv0ZzBNliJRwFGAcuLr/NsYsq6LLzUvYxwgUtmeoS8uJKoRoklk+VwuCQt/F0=
before_install:
- sudo apt-get update
- sudo apt-get install --only-upgrade -y oracle-java8-installer
- mkdir -p ~/.gnupg
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in secring.gpg.enc -out ~/.gnupg/secring.gpg
  -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in pubring.gpg.enc -out ~/.gnupg/pubring.gpg
  -d
- echo "<settings><servers><server><id>ossrh</id><username>\${OSSRH_JIRA_USERNAME}</username><password>\${OSSRH_JIRA_PASSWORD}</password></server></servers></settings>"
  > ~/.m2/settings.xml
install:
- wget ${ACTIVATOR_ZIP_URL}
- unzip -q ${ACTIVATOR_ZIP_FILE}
script:
- mvn -f pom2.xml clean install gpg:sign -Dgpg.passphrase="${GPG_PASSPHRASE}" --settings
  ~/.m2/settings.xml
- .travis/deploy.sh
after_success:
- 
after_script:
- rm ~/.gnupg/secring.gpg
- rm ~/.gnupg/pubring.gpg
- rm ~/.m2/settings.xml
notifications:
  email: true
branches:
  only:
  - master
scala:
- 2.11.8
cache:
  directories:
  - .autoconf
  - ~/.m2
  - ~/.sbt
  - ~/.ivy
